version: "3.8"  # Specify the version of Docker Compose

services:
  ocr-web:
    # ... existing config ...
    volumes:
      - pdf-chunks:/tmp/pdf-chunks

  processing-agent:
    build: ./agents/processing
    environment:
      - PDF_TEMP_DIR=/tmp/pdf-chunks
    volumes:
      - pdf-chunks:/tmp/pdf-chunks
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pdf-chunks:
  redis-data:
