version: "3.8"
services:
  primary-agent:
    build:
      context: ./agents/primary
      dockerfile: Dockerfile
    container_name: primary-agent
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
