services:
  ocr-web:
    build:
      context: ./services/ocr-web
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - pdf-chunks:/tmp/pdf-chunks

  processing-agent:
    build: ./agents/processing
    environment:
      - PDF_TEMP_DIR=/tmp/pdf-chunks
    volumes:
      - pdf-chunks:/tmp/pdf-chunks
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pdf-chunks:
  redis-data:
